# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('multimedia', models.BooleanField()),
                ('cost', models.IntegerField()),
                ('image', models.CharField(max_length=250)),
                ('description', models.CharField(default=b'', max_length=1000)),
                ('operation_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.OperationSystem')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='phone',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Producer'),
        ),
        migrations.AddField(
            model_name='phone',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Type'),
        ),
    ]
